import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  // Check if the user is signed in
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {user.isSignedIn ? <SignOutButton /> : (
            <div className='flex justify-center'>
              <SignInButton />
            </div>
            )}
          </div>
          <div className='flex flex-col'>
            {[...data, ...data]?.map((post) => (
              <div key={post.id} className='p-8 border-b border-slate-400'>{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
